Criação do entidade, do repositório e da service para o alert
SouJunior/vagas-api pull request #167
Opened 2024-09-02 18:59 UTC by leticiazalasik

Us #686

2024-09-03 13:47 UTC, MikaelMelo1 requested changes
Comentei os Arquivos que precisam ser arrumados.

2024-09-03 13:47 UTC, MikaelMelo1 commented on src/database/entities/alert.entity.ts
Pra facilitar as consultas e também pra otimização, pode deixar o userId como coluna.

2024-09-03 13:47 UTC, MikaelMelo1 commented on src/modules/alert/repository/alerts.repository.ts
Renomea o findUserById pra findAlertsByUserId, pq o nome pode causar confusão, assim ele fica mais claro...

Você irá também implementar o método findSimilarAlert?

2024-09-03 13:47 UTC, MikaelMelo1 commented on src/modules/alert/service/alerts.service.ts
Renomeie o  findEmailUser pra getUserEmailByAlertId.

Você irá implementar o Método createAlert?

2024-09-06 13:24 UTC, leticiazalasik commented on src/database/entities/alert.entity.ts
Feito! Ótima colocação

2024-09-06 13:25 UTC, leticiazalasik commented on src/modules/alert/repository/alerts.repository.ts
Renomeção feita,  findSimilarAlert será discutido para próxima sprint.

2024-09-06 13:25 UTC, leticiazalasik commented on src/modules/alert/service/alerts.service.ts
Ambos feitos, obrigada. Favor só dar um ok para createAlert

2024-09-09 17:19 UTC, MikaelMelo1 reviewed
Excelente!

2024-10-04 20:06 UTC, merged