feat Criação do Serviço de Candidatura
SouJunior/vagas-api pull request #179
Opened 2024-10-11 08:49 UTC by joselazarojunior

Criação do Serviço de Candidatura:
    
Serviço CandidaturaService:
     ◦ create(createCandidaturaDto: CreateCandidaturaDto): Criar uma nova candidatura.
     ◦ getCandidaturasByUsuarioId(usuarioId: UUID): Retornar todas as candidaturas em andamento de um usuário.
     ◦ encerrarCandidatura(id: UUID): Atualizar o status da candidatura para "Encerrada" ou "Sem interesse".

Lógica de Status:
     ◦ Gerenciar os status de cada candidatura: "Em andamento", "Encerrada", e "Sem interesse".

2024-10-14 17:58 UTC, MikaelMelo1 requested changes

2024-10-14 17:58 UTC, MikaelMelo1 commented on src/candidacy/candidacy.service.ts
> +    candidacy.status = 'Em andamento';
no candicacy.status, usar o ENUM, A Léticia fez o dela, pode usar o mesmo.

2024-10-14 17:58 UTC, MikaelMelo1 commented on src/candidacy/candidacy.service.ts
> +  async closeCandidacy(id: string, status: 'Encerrada' | 'Sem interesse'): Promise<CandidacyEntity> {
Mesma situação do ENUM na parte de status.
Também é importante lançar tratamento de erro.

2024-10-14 17:58 UTC, MikaelMelo1 commented on src/candidacy/candidacy.service.ts
> +  async create(createCandidacyDto: CreateCandidacyDto): Promise<CandidacyEntity> {
Antes de criar uma nova candidatura seria bom validar os dados primeiramente. (Try e Catch (cuida na parte do tratamento de erro))

2024-10-14 17:58 UTC, MikaelMelo1 commented on src/candidacy/dto/create-candidacy.dto.ts
Se você quiser pode adicionar mensagens de erro dentro do dto. Mensagens personalizadas.

2024-10-14 17:58 UTC, MikaelMelo1 commented on src/database/entities/candidacy.entity.ts
> +  @Column({ type: 'enum', enum: ['em andamento', 'encerrada', 'sem interesse'] })
Usar enum em vez de passar direto.

2024-10-14 17:58 UTC, MikaelMelo1 commented on src/database/entities/candidacy.entity.ts
> +  dataCandidatura: Date;
Deixar em inglês

2024-10-14 17:58 UTC, MikaelMelo1 commented on src/database/entities/candidacy.entity.ts
> +  dataEncerramento: Date;
Deixar em inglês

2024-10-14 17:58 UTC, MikaelMelo1 commented on src/modules/candidacy/repository/candidacy.repository.ts
Melhoria: 
- Para maior precisão troque o no findAllByUserId que está com Promise<CandidacyEntity[]> por Promise<CandidacyEntity>[]>
- No updateStatus: Promise<CandidacyEntity | undefined> por Promise<CandidacyEntity | null> pra ter a possibilidade de não encontrar a candidatura
- No updateStatus: utilize o findOne pra buscar diretamente a candidatura pode também melhorar na parte de não precisar percorrer todo o array, já que vai atualizar o status ou você que atualizar de todos?
-  No updateStatus melhore a parte de tratamento de erro, por exemplo retirando o undefined por um throw new notfoundexception por exemplo ou até mesmo um sucess: false, error.

2024-10-22 05:38 UTC, joselazarojunior commented on src/candidacy/candidacy.service.ts
> +  async create(createCandidacyDto: CreateCandidacyDto): Promise<CandidacyEntity> {
Feito!

2024-10-22 05:38 UTC, joselazarojunior commented on src/candidacy/candidacy.service.ts
> +    candidacy.status = 'Em andamento';
OK! Feito!

2024-10-22 05:39 UTC, joselazarojunior commented on src/candidacy/candidacy.service.ts
> +  async closeCandidacy(id: string, status: 'Encerrada' | 'Sem interesse'): Promise<CandidacyEntity> {
Feito!

2024-10-22 05:41 UTC, joselazarojunior commented on src/candidacy/dto/create-candidacy.dto.ts
Deixei as mensagens nos serviços mesmo. Vamos verificar depois a necessidade de padronizar as mensagens?

2024-10-22 05:42 UTC, joselazarojunior commented on src/database/entities/candidacy.entity.ts
> +  @Column({ type: 'enum', enum: ['em andamento', 'encerrada', 'sem interesse'] })
Feito!

2024-10-22 05:45 UTC, joselazarojunior commented on src/database/entities/candidacy.entity.ts
> +  dataCandidatura: Date;
Feito!

2024-10-22 05:45 UTC, joselazarojunior commented on src/database/entities/candidacy.entity.ts
> +  dataEncerramento: Date;
Feito!

2024-10-22 06:57 UTC, joselazarojunior commented on src/modules/candidacy/repository/candidacy.repository.ts
Feito! 
Só não compreendi essa orientação:

Para maior precisão troque o no findAllByUserId que está com Promise<CandidacyEntity[]> por Promise[]>

2024-10-23 19:45 UTC, MikaelMelo1 requested changes

2024-10-23 19:45 UTC, MikaelMelo1 commented on src/database/entities/candidacy.entity.ts
> +  dateaClosing: Date;
dateClosing, corrija o nome por favor.

2024-10-23 19:45 UTC, MikaelMelo1 commented on src/database/entities/candidacy.entity.ts
import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { UsersEntity } from './users.entity';
import { JobsEntity } from './jobs.entity';
import { CandidacyStatus } from './candidacy-status.enum';

@Entity('tb_candidacies', { indexes: [{ columns: ['userId'] }, { columns: ['jobId'] }] })
export class CandidacyEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('uuid')
  jobId: string;

  @Column('uuid')
  userId: string;

  @Column({ type: 'enum', enum: CandidacyStatus })
  status: CandidacyStatus;

  @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  dateCandidacy: Date;

  @Column({ 
    type: 'timestamp', 
    nullable: true, 
    onUpdate: () => 'CURRENT_TIMESTAMP' 
  })
  dateClosing: Date;

  @ManyToOne(() => UsersEntity)
  @JoinColumn({ name: 'userId' })
  user: UsersEntity;

  @ManyToOne(() => JobsEntity)
  @JoinColumn({ name: 'jobId' })
  job: JobsEntity;
}

2024-10-23 19:45 UTC, MikaelMelo1 commented on src/database/entities/candidancy-status.enum.ts
Ok

2024-10-23 20:40 UTC, joselazarojunior commented on src/database/entities/candidacy.entity.ts
ok! não tinha reparado no "a" ali!!

2024-10-23 20:40 UTC, joselazarojunior commented on src/database/entities/candidacy.entity.ts
> +  dateaClosing: Date;
ok! não tinha reparado no "a" ali!!

2024-10-25 12:32 UTC, MikaelMelo1 requested changes

2024-10-25 12:32 UTC, MikaelMelo1 commented on src/database/entities/candidacy.entity.ts
Sem problemas, faz um commit com o código que mandei pra você por aqui mesmo

2024-10-25 16:26 UTC, joselazarojunior commented on src/database/entities/candidacy.entity.ts
Feito!!

2024-10-26 15:12 UTC, joselazarojunior commented on src/database/entities/candidacy.entity.ts
Feito!

2024-10-26 20:31 UTC, MikaelMelo1 reviewed
Ok.

2024-12-05 18:50 UTC, merged