Refactor/cleanup and readme improvements
SouJunior/vagas-api pull request #187
Opened 2024-11-21 17:44 UTC by raiane-oliveira

### Alterações

- Mudei a configuração do certificado SSL na conexão com o banco de dados para ser usado apenas em ambiente de produção;
- Adicionei o arquivo `.env.example` com todas as variáveis de ambiente utilizadas na aplicação;
- Melhorei o README para deixar algumas informações mais claras.

2024-11-28 01:49 UTC, sonnesen requested changes

2024-11-28 01:49 UTC, sonnesen commented on .gitignore
> -.env
É uma boa prática incluir o arquivo .env no .gitignore.

2024-11-28 20:31 UTC, raiane-oliveira commented on .gitignore
> -.env
O arquivo `.env.example` estava dentro do `.gitignore` e o `.env` estava duplicado, por isso removi

2024-11-29 00:35 UTC, sonnesen approved these changes

2024-11-29 00:36 UTC, merged